# Generated by Django 5.1 on 2024-08-19 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoBodega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("S", "6 metros cuadrados - Sencilla"),
                            ("Q", "12 metros cuadrados - Sencilla"),
                            ("Q2", "12 metros cuadrados - Químicos Industriales"),
                            ("B", "20 metros cuadrados - Material Orgánico"),
                        ],
                        max_length=2,
                    ),
                ),
                ("metros_cuadrados", models.PositiveIntegerField()),
                ("preparada_quimicos", models.BooleanField(default=False)),
                ("preparada_organico", models.BooleanField(default=False)),
                ("hermetica", models.BooleanField(default=False)),
                ("precio_mensual", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bodega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_unico", models.CharField(max_length=100, unique=True)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.tipobodega"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "noticia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.noticia"
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "noticia")},
            },
        ),
    ]
